title: Apprendre le réseau
category: Enseignement
leçons:
  1: Comment les ordinateurs communiquent-ils?
  2: "L’Internet des Objets : Comment les ordinateurs contrôlent-il contrôlent-ils d’autres ordinateurs?"
  3: Protocole de configuration d’adresse dynamique (DHCP)
  4: Système de nom de domaine (DNS)
